# Generated by Django 4.1.2 on 2022-11-06 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('path', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'image',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'news',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=500)),
                ('curiosity', models.CharField(max_length=500)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.image')),
            ],
            options={
                'db_table': 'history',
                'ordering': ('battle_name',),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('catchphrase', models.CharField(max_length=300)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.image')),
            ],
            options={
                'db_table': 'chapter',
                'ordering': ('name',),
            },
        ),
    ]
