# Generated by Django 4.1.2 on 2022-12-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=70, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
